name = "yggdrasil-worker"
main = "src/index.js"
compatibility_date = "2023-10-02"

[[d1_databases]]
binding = "DB"
database_name = "yggdrasil"
database_id = "f02cf4ed-7ef5-4078-adbb-009029959d3b"

[vars]
SKIN_DOMAINS = ["localhost", "127.0.0.1"]
PUBKEY = "-----BEGIN PUBLIC KEY-----\nBase64==\n-----END PUBLIC KEY-----\n"
VERSION = "20231005"
SERVER_NAME = "Minecraft auth server"
